# Bot Configuration
BOT_PREFIX: '~'
BOT_PERMISSIONS: 8  # Administrator permissions

# Query Limits
MAX_QUERIES_PER_DAY: 10
MAX_SMART_QUERIES_PER_DAY: 3

# Logging
LOG_LEVEL: 'INFO'

# Repository Settings
DEFAULT_BRANCH: 'main'

# Discord Settings
GUILD_ID: ''  # Optional: Specify a guild ID if you want the bot to only work in a specific server

# Command Cooldowns (in seconds)
COOLDOWNS:
  search: 5
  query: 10
  smartquery: 30

# Feature Flags
ENABLE_SMART_QUERY: true
ENABLE_ERROR_REPORTING: true

# Database Settings
DB_NAME: 'bot_data.db'
DB_MAX_CONNECTIONS: 5

# API Settings
API_TIMEOUT: 60  # Timeout for API requests in seconds
API_RETRIES: 3   # Number of retries for failed API requests

# Miscellaneous
EMBED_COLOR: 0x3498db  # Discord embed color (blue)